### ISSUE TITLE
Create a form/mailing list 

### ISSUE THREAD

**Issue by BatoolMM** [ARab-R/ARab_R#3]
Create a forum or a mailing list and 'Join us' button on the landing page!

**Comment by Hussain-Alsalman** [comment]
This can be done via 3rd party services with annual charge for subscription. The solution in mind is to run a workflow that aggregate the recent posts and send them in an email to subscribed users. This will require a subscription to a mailing list service such as [tinyletter](http://tinyletter.com/) and a workflow trigger such as [Zapier](https://zapier.com) or [IFTTT](https://ifttt.com) for aggregation actions.
