### ISSUE TITLE
Starting your own useR or R-Ladies group in MENA

### ISSUE THREAD

**Issue by BatoolMM** [ARab-R/ARab_R#5]
Write an Arabic instruction (in R Markdown format) about starting your own useR or R-Ladies group.

**Comment by MounaBelaid** [comment]
Hello! I'm working on this!

**Comment by MounaBelaid** [comment]
Hello,
 I'm working on it!

**Comment by BatoolMM** [comment]
Thank you @MounaBelaid, let me know if you need any help!

**Comment by MounaBelaid** [comment]
Hello team,
I've just added two posts about the onboarding process to start an R-Ladies chapter and an R User Group. That was challenging for me as that was the first time I wrote in R in arabic and I'm not too used to writing in Arabic so please don't hesitate to make any improvements!

**Comment by BatoolMM** [comment]
Thank you @MounaBelaid ❤️ - can I ask where did you add them, please?

**Comment by MounaBelaid** [comment]
Thank you! ❤️ I've added them in the Posts folder.

**Comment by BatoolMM** [comment]
Your writing is way better than mine, it looks awesome - only minor corrections for punctuation! You are encouraged to submit posts as PRs so others can know that something has been added/changed to the website and circulate it to our network.

**Comment by MounaBelaid** [comment]
Thank you! You are right, I will pay attention next time.
